# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4

#COPY config/sg/ config/sg/
#COPY bin/ bin/

# Search Guard plugin
# https://github.com/floragunncom/search-guard/wiki
#RUN elasticsearch-plugin install --batch com.floragunn:search-guard-6:6.2.4-22.1 
#RUN chmod +x plugins/search-guard-6/tools/*.sh
#RUN ./plugins/search_guard_6/tools/install_demo_config.sh
#RUN chown -R elasticsearch config/sg
#RUN chmod -R go= config/sg/

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
